jobs:
  - script: >
      folder('project-a') {
        displayName('Project A')
        description('Folder for project A')
      }
  - script: >
      pipelineJob('project-a/first') {
        displayName('First pipeline')
        description('First pipeline to play around Jenkins')
        definition {
          cps {
              script('''
                pipeline {
                    agent {
                          label 'alpine'
                    }
                    stages {
                        stage('Init') {
                            steps {
                                echo 'Stage 1 '
                            }
                        }
                        stage('Build') {
                            
                            steps {
                                echo 'Stage 2 '
                            }
                        }
                        stage('Post Build') {
                            steps {
                                echo 'Stage 3 Post Build'
                            }
                        }
                    }
                }
                '''.stripIndent())
                sandbox()
            }
        }
      }
