jobs:
  - script: >
      folder('project-a') {
        displayName('Project A')
        description('Folder for project A')
      }
  - script: >
      pipelineJob('project-a/hello') {
        displayName('Hello World')
        description('First pipeline to print Hello World')
        definition {
          cps {
              script('''
                pipeline {
                    agent any
                    stages {
                        stage('Init') {
                            steps {
                                echo 'Stage 1 Init'
                            }
                        }
                        stage('Build') {
                            input {
                                    message "Should we continue?"
                                    ok "Yes"
                                  }
                            steps {
                                echo 'Stage 2 Build'
                            }
                        }
                        stage('Post Build') {
                            steps {
                                echo 'Stage 3 Post Build'
                            }
                        }
                    }
                }
                '''.stripIndent())
                sandbox()
            }
        }
      }

# jobs:
#   - script: >
#       folder('project-a') {
#         displayName('Project A')
#         description('Folder for project A')
#       }
#   - script: >
#       pipelineJob('project-a/hello') {
#         displayName('Hello World')
#         description('First pipeline to print Hello World')
#         definition {
#           cpsScm {
#               scriptPath('jenkinsFile')
#               scm {
#                   git('https://github.com/shravani-c/jenkins.git')
#               }
#           }
#         }
#       }
